# Ejercicio 4

Teniendo en cuenta la variable `altura_m` que se encuentra en el dataset pacientes.csv trabajado en el Ejercicio N°2, genere una tabla de frecuencias en la que las observaciones se encuentren segmentadas en subintervalos de 10 cm de amplitud que estén “cerrados por izquierda”, es decir, que tengan la forma [`extremo_inferior`, `extremo_superior`].

La tabla de frecuencias generada deberá contener columnas en las que se especifiquen las frecuencias absolutas, relativas y relativas acumuladas correspondientes a cada subintervalo. ¿Qué porcentaje de las personas del dataset tienen una altura menor a 1.8 m?

In [17]:
# Cargamos los paquetes necesarios y el df de pacientes

import numpy as np
import pandas as pd

df = pd.read_csv('../datasets/pacientes.csv', sep=';', encoding = 'latin_1')
df.head()

,codigo_paciente,peso_inicial_kg,peso_final_kg,altura_m,sexo,tiempo_tratamiento_dias
0,398911,78,72,"1,8",F,583
1,398912,68,68,"1,75",F,159
2,398913,92,70,"1,85",F,70
3,398914,66,64,"1,65",M,41
4,398915,51,50,"1,55",F,30

In [19]:
# La altura es una variable de tipo float.

df["altura_m"] = df["altura_m"].str.replace(",", ".")
df['altura_m'] =  pd.to_numeric(df['altura_m'], errors='coerce')
df.head()

,codigo_paciente,peso_inicial_kg,peso_final_kg,altura_m,sexo,tiempo_tratamiento_dias
0,398911,78,72,1.80,F,583
1,398912,68,68,1.75,F,159
2,398913,92,70,1.85,F,70
3,398914,66,64,1.65,M,41
4,398915,51,50,1.55,F,30

In [31]:
# Construir intervalos de 10 cm

min_alt = df["altura_m"].min()
max_alt = df["altura_m"].max()

bins = np.arange(min_alt, max_alt + 0.1, 0.1)

In [23]:
# Creamos intervalos cerrados a izquierda y abiertos a derecha

df["intervalo"] = pd.cut(df["altura_m"], bins=bins, right=False)

In [25]:
# Cosntruimos la tabla de fecuencias

freq_abs = df["intervalo"].value_counts().sort_index()
freq_rel = df["intervalo"].value_counts(normalize=True).sort_index()
freq_rel_acum = freq_rel.cumsum()

tabla = pd.DataFrame({
                        "frecuencia": freq_abs,
                        "frecuencia_relativa": freq_rel,
                        "frecuencia_relativa_acumulada": freq_rel_acum
                    })

tabla

            frecuencia  frecuencia_relativa  frecuencia_relativa_acumulada
intervalo
[1.5, 1.6)          12                 0.24                           0.24
[1.6, 1.7)          20                 0.40                           0.64
[1.7, 1.8)          11                 0.22                           0.86
[1.8, 1.9)           7                 0.14                           1.00

In [32]:
# Porcentaje de personas con altura < 1.8 m

print('El promedio es:', (df["altura_m"] < 1.8).mean() * 100,'%')

El promedio es: 82.0 %